FROM python:3.8-alpine

WORKDIR /NA_NLP

COPY ./requirements.txt /app/requirements.txt

# switch working directory


# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

# copy every content from the local file to the image
COPY . /app

# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]


CMD ["FLASK_APP=app.py flask run"]
